# This is a basic workflow to help you get started with Actions

name: Opam build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Concurrency group used to cancel old runs
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref }}"
  cancel-in-progress: true
permissions:
  contents: read
env:
  JOBS: 4

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # Needs to be ubuntu-22.04 or earlier because avsm/setup-ocaml@v1 is broken in later
    # ubuntu images
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v4
        with:
          path: "~/.opam"
          key: opam-${{github.base_ref}}-${{github.ref}}
          restore-keys: |
            opam--refs/heads/${{github.base_ref}}

      # Set up OCaml and opam
      - name: Install OCaml
        # We use v1 instead of the most recent version because caching doesn't work well with
        # more recent versions
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.14.2

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install coq.8.18.0 coq-equations.1.3+8.18 coq-mathcomp-ssreflect.2.1.0 coq-mathcomp-analysis.1.0.0 coq-extructures.0.4.0 coq-deriving.0.2.0 coq-mathcomp-word.3.2 coq-mathcomp-zify.1.5.0+2.0+8.16
          opam exec -- make -j${{ env.JOBS }}

      # Build coqdoc documentation
      - name: Build documentation
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "::group::Running coqdoc"
          opam exec -- make -j${{ env.JOBS }} html
          echo "::endgroup::"

      # Upload documentation
      - name: Prepare documentation for deployment
        # Only upload and deploy documentation when pushing on main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  # Deploy coqdoc generated documentation to GitHub pages
  deploy-docs:
    # Only deploy documentation when pushing on main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
